export const statusOptions = [
  { id: 'progress', title: 'Em progresso' },
  { id: 'finished', title: 'Zerado' },
];

export const platformOptions = [
  { id: '', title: 'Selecione onde zerou' },
  { id: 'PC', title: 'PC' },
  { id: 'Steam', title: 'Steam' },
  { id: 'PlayStation', title: 'PlayStation' },
  { id: 'PlayStation 2', title: 'PlayStation 2' },
  { id: 'PlayStation 3', title: 'PlayStation 3' },
  { id: 'PlayStation 4', title: 'PlayStation 4' },
  { id: 'PlayStation 5', title: 'PlayStation 5' },
  { id: 'PSP', title: 'PSP' },
  { id: 'PlayStation Vita', title: 'PlayStation Vita' },
  { id: 'Xbox', title: 'Xbox' },
  { id: 'Xbox 360', title: 'Xbox 360' },
  { id: 'Xbox One', title: 'Xbox One' },
  { id: 'Xbox Series X|S', title: 'Xbox Series X|S' },
  { id: 'NES', title: 'Nintendo Entertainment System' },
  { id: 'Super Nintendo', title: 'Super Nintendo' },
  { id: 'Nintendo 64', title: 'Nintendo 64' },
  { id: 'Nintendo GameCube', title: 'Nintendo GameCube' },
  { id: 'Nintendo Wii', title: 'Nintendo Wii' },
  { id: 'Nintendo Wii U', title: 'Nintendo Wii U' },
  { id: 'Nintendo Switch', title: 'Nintendo Switch' },
  { id: 'Nintendo Switch 2', title: 'Nintendo Switch 2' },
  { id: 'Game Boy', title: 'Game Boy' },
  { id: 'Game Boy Color', title: 'Game Boy Color' },
  { id: 'Game Boy Advance', title: 'Game Boy Advance' },
  { id: 'Nintendo DS', title: 'Nintendo DS' },
  { id: 'Nintendo 3DS', title: 'Nintendo 3DS' },
  { id: 'Sega Master System', title: 'Sega Master System' },
  { id: 'Mega Drive', title: 'Mega Drive / Genesis' },
  { id: 'Sega Saturn', title: 'Sega Saturn' },
  { id: 'Dreamcast', title: 'Dreamcast' },
  { id: 'Arcade', title: 'Arcade' },
  { id: 'Mobile', title: 'Android / iOS' },
  { id: 'Outro', title: 'Outro' },
];
